version: '3.7'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
  node-app:
    build: ./gate-simulator
    image: node-app:1.1
    ports:
      - '9999:9999'